CREATE TABLE IF NOT EXISTS ANALYTICS_EVENTS (
    id SERIAL PRIMARY KEY,
    user_id INTEGER,
    event_type VARCHAR(50) NOT NULL,
    properties JSONB,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_analytics_type ON ANALYTICS_EVENTS(event_type);
CREATE INDEX IF NOT EXISTS idx_analytics_user ON ANALYTICS_EVENTS(user_id);
