CREATE TABLE IF NOT EXISTS ASSET_DATA_CACHE (
    asset_key VARCHAR(255) PRIMARY KEY,
    data_blob BLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);