"""
Weighting Profiles for Strategy Leaderboard

Provides preset weighting schemes for different investor personas.
Profiles are organized by strategy category for better UX.
"""
from typing import Dict, List


WEIGHTING_PROFILES = {
    # ========================================
    # UNIVERSAL PROFILE (shows in all categories)
    # ========================================
    # ========================================
    # ACCUMULATION STRATEGIES (CONTRIBUTION_ONLY)
    # ========================================
    'balanced_accumulation': {
        'name': 'Balanced Accumulation',
        'description': 'Balanced growth and risk management',
        'detailed_description': """
**Who it's for:** Investors building wealth who want a middle-ground approach.

**Philosophy:** Balances the need for growth (Implementation of compounding) with the need for safety (Risk Score). 
It avoids the extremes of "Growth at all costs" or "Safety first", aiming for consistent, reliable wealth building.

**Key Metrics:**
- 25% Capital Efficiency (ROI)
- 25% Risk Score (Protection)
- 20% Legacy Score (Terminal Wealth)
- 15% Accumulation Velocity (Growth Rate)
- 15% Contribution Efficiency (Valuable Additions)
        """,
        'emoji': '⚖️',
        'applicable_categories': ['CONTRIBUTION_ONLY'],
        'category_label': 'accumulation',
        'weights': {
            'pv_score': 0.00,
            'purchasing_power_score': 0.00,
            'stability_score': 0.00,
            'risk_score': 0.25,
            'robustness_score': 0.00,
            'capital_efficiency_score': 0.25,
            'legacy_score': 0.20,
            'consumption_ratio_score': 0.00,
            'coast_fire_score': 0.00,
            'accumulation_velocity_score': 0.15,
            'contribution_efficiency_score': 0.15,
        }
    },
    
    # ========================================
    # ACCUMULATION STRATEGIES (CONTRIBUTION_ONLY)
    # ========================================
    'aggressive_growth': {
        'name': 'Aggressive Growth',
        'description': 'Maximize wealth accumulation, high risk tolerance',
        'detailed_description': """
**Who it's for:** Young investors with long time horizons (20+ years) and high risk tolerance.

**Philosophy:** Growth at all costs. Volatility is just noise—what matters is terminal wealth. 
This profile heavily prioritizes capital efficiency (25%), legacy score (25%), and Coast FIRE (10%).

**Best for:** Investors under 40, those with stable income sources, or anyone prioritizing maximum long-term wealth over stability.

**Key Metrics:**
- 25% Capital Efficiency (maximize ROI on contributions)
- 25% Legacy Score (terminal wealth is the goal)
- 10% Coast FIRE (reach financial independence faster)
- 10% Accumulation Velocity (CAGR)
        """,
        'emoji': '🚀',
        'applicable_categories': ['CONTRIBUTION_ONLY'],
        'category_label': 'accumulation',
        'weights': {
            'pv_score': 0.00,  # N/A for contributions
            'purchasing_power_score': 0.00,  # N/A for contributions
            'stability_score': 0.00,  # N/A
            'risk_score': 0.10,  # Only catastrophic risk matters
            'robustness_score': 0.00,  # All acc strategies get 99/100 - not useful
            'capital_efficiency_score': 0.25,  # DOMINANT
            'legacy_score': 0.25,  # DOMINANT - terminal wealth
            'consumption_ratio_score': 0.00,  # N/A
            'coast_fire_score': 0.10,
            'accumulation_velocity_score': 0.10,
            'contribution_efficiency_score': 0.05,  # Growth generated by strategy
        }
    },
    
    'coast_fire_optimizer': {
        'name': 'Coast FIRE Optimizer',
        'description': 'Reach financial independence as fast as possible',
        'detailed_description': """
**Who it's for:** FIRE (Financial Independence, Retire Early) enthusiasts focused on reaching Coast FIRE.

**Philosophy:** The goal is to reach a point where you can stop contributing and growth alone will hit retirement targets. 
This profile uniquely emphasizes the Coast FIRE metric (30%), along with capital efficiency and moderate risk management.

**Best for:** Those pursuing financial independence, barista FIRE seekers, or anyone wanting the option to stop working ASAP.

**Key Metrics:**
- 30% Coast FIRE Score (when can contributions stop?)
- 15% Capital Efficiency (maximize growth per dollar saved)
- 15% Risk Score (don't blow up before reaching coast)
- 10% Accumulation Velocity (get there faster)
        """,
        'emoji': '🏖️',
        'applicable_categories': ['CONTRIBUTION_ONLY'],
        'category_label': 'accumulation',
        'weights': {
            'pv_score': 0.00,  # N/A for contributions
            'purchasing_power_score': 0.00,  # N/A for contributions
            'stability_score': 0.00,
            'risk_score': 0.15,
            'robustness_score': 0.00,  # All acc strategies get 99/100 - not useful
            'capital_efficiency_score': 0.15,
            'legacy_score': 0.10,
            'consumption_ratio_score': 0.00,
            'coast_fire_score': 0.30,  # DOMINANT - main goal
            'accumulation_velocity_score': 0.10,
            'contribution_efficiency_score': 0.15,  # Redistributed from robustness
        }
    },
    
    'steady_saver': {
        'name': 'Steady Saver',
        'description': 'Conservative accumulation with capital preservation',
        'detailed_description': """
**Who it's for:** Conservative accumulators, those nearing retirement transition, or low risk tolerance savers.

**Philosophy:** Slow and steady wins the race. Preserve capital, grow cautiously, avoid disasters. 
This profile heavily weights risk management (30%) and robustness (10%), ensuring strategies work in all market conditions.

**Best for:** Individuals 10-15 years from retirement, those with moderate savings, or anyone prioritizing safety over maximum returns.

**Key Metrics:**
- 30% Risk Score (avoid catastrophic losses)
- 20% Legacy Score (preserve what you save)
- 15% Purchasing Power (maintain real wealth - though limited for contribution strategies)
- 10% Robustness (must work in bear markets)
        """,
        'emoji': '🏦',
        'applicable_categories': ['CONTRIBUTION_ONLY'],
        'category_label': 'accumulation',
        'weights': {
            'pv_score': 0.00,  # N/A for contributions
            'purchasing_power_score': 0.00,  # N/A for contributions
            'stability_score': 0.00,
            'risk_score': 0.30,  # DOMINANT - safety first
            'robustness_score': 0.00,  # All acc strategies get 99/100 - not useful
            'capital_efficiency_score': 0.15,
            'legacy_score': 0.20,
            'consumption_ratio_score': 0.00,
            'coast_fire_score': 0.05,
            'accumulation_velocity_score': 0.05,  # Redistributed from robustness
            'contribution_efficiency_score': 0.05,  # Redistributed from robustness
        }
    },
    
    'balanced_accumulator': {
        'name': 'Balanced Accumulator',
        'description': 'Moderate growth with balanced risk',
        'detailed_description': """
**Who it's for:** Middle-aged investors (40-55) with moderate risk tolerance and diversified goals.

**Philosophy:** Balance growth, safety, and consistency. This profile doesn't chase maximum returns, 
but also doesn't obsess over safety. It's the Goldilocks approach for wealth building.

**Best for:** Investors who want solid growth without extreme volatility, those uncertain about their risk tolerance, 
or anyone seeking a well-rounded accumulation strategy.

**Key Metrics:**
- 20% Capital Efficiency (good ROI)
- 20% Risk Score (reasonable safety)
- 15% Present Value (total value)
- 15% Legacy Score (meaningful terminal wealth)
        """,
        'emoji': '📊',
        'applicable_categories': ['CONTRIBUTION_ONLY'],
        'category_label': 'accumulation',
        'weights': {
            'pv_score': 0.00,  # N/A for contributions
            'purchasing_power_score': 0.00,  # N/A for contributions
            'stability_score': 0.00,
            'risk_score': 0.20,
            'robustness_score': 0.00,  # All acc strategies get 99/100 - not useful
            'capital_efficiency_score': 0.20,
            'legacy_score': 0.15,
            'consumption_ratio_score': 0.00,
            'coast_fire_score': 0.10,
            'accumulation_velocity_score': 0.05,  # Redistributed from robustness
            'contribution_efficiency_score': 0.10,  # Redistributed from robustness
        }
    },
    
    # ========================================
    # WITHDRAWAL STRATEGIES (WITHDRAWAL_ONLY)
    # ========================================
    'balanced_withdrawal': {
        'name': 'Balanced Withdrawal',
        'description': 'Balanced income, safety, and preservation',
        'detailed_description': """
**Who it's for:** Retirees seeking a standard, reliable withdrawal plan.

**Philosophy:** Equally weights the three pillars of retirement: Income Security (Risk/PV), Income Quality (Stability/Purchasing Power), and Legacy. 
It's the "60/40 portfolio" equivalent of weighting profiles—boring but effective.

**Key Metrics:**
- 25% Risk Score (Don't run out)
- 20% Present Value (Good total income)
- 20% Purchasing Power (Keep up with inflation)
- 15% Stability (Predictable checks)
- 20% Legacy (Leave something behind)
        """,
        'emoji': '⚖️',
        'applicable_categories': ['WITHDRAWAL_ONLY'],
        'category_label': 'withdrawal',
        'weights': {
            'pv_score': 0.20,
            'purchasing_power_score': 0.20,
            'stability_score': 0.15,
            'risk_score': 0.25,
            'robustness_score': 0.00,
            'capital_efficiency_score': 0.00,
            'legacy_score': 0.20,
            'consumption_ratio_score': 0.00,
            'coast_fire_score': 0.00,
            'accumulation_velocity_score': 0.00,
            'contribution_efficiency_score': 0.00,
        }
    },
    'conservative': {
        'name': 'Conservative Retiree',
        'description': 'Prioritize safety and capital preservation',
        'detailed_description': """
**Who it's for:** Retirees who value peace of mind above all else. Those who can't afford big losses or don't want sleepless nights.

**Philosophy:** Preservation first, growth second. This profile heavily weights risk management (55% combined on risk and stability), 
ensuring strategies won't experience severe drawdowns even in market crashes. Purchasing power and modest legacy matter, 
but only if they don't compromise safety.

**Best for:** Risk-averse individuals, those with fixed pensions, or retirees with limited capacity to recover from losses.
        """,
        'emoji': '🛡️',
        'applicable_categories': ['WITHDRAWAL_ONLY'],
        'category_label': 'withdrawal',
        'weights': {
            'pv_score': 0.10,
            'purchasing_power_score': 0.20,
            'stability_score': 0.25,
            'risk_score': 0.30,  # DOMINANT
            'robustness_score': 0.00,
            'capital_efficiency_score': 0.00,
            'legacy_score': 0.15,
            'consumption_ratio_score': 0.00,
            'coast_fire_score': 0.00,  # N/A
            'accumulation_velocity_score': 0.00,  # N/A
            'contribution_efficiency_score': 0.00,  # N/A
        }
    },
    
    'income_focused': {
        'name': 'Income Focused',
        'description': 'Maximize stable, inflation-adjusted income',
        'detailed_description': """
**Who it's for:** Retirees who prioritize reliable monthly income that keeps pace with inflation. Those replacing a paycheck.

**Philosophy:** Income is king. This profile overwhelmingly favors strategies that deliver consistent, inflation-protected withdrawals 
(85% combined on PV, purchasing power, and stability). Growth and efficiency are secondary—what matters is dependable cash flow.

**Best for:** Early retirees living entirely off portfolio withdrawals, or those transitioning from salary to retirement income.
        """,
        'emoji': '💰',
        'applicable_categories': ['WITHDRAWAL_ONLY'],
        'category_label': 'withdrawal',
        'weights': {
            'pv_score': 0.35,  # DOMINANT
            'purchasing_power_score': 0.30,  # DOMINANT
            'stability_score': 0.20,
            'risk_score': 0.10,
            'robustness_score': 0.00,
            'capital_efficiency_score': 0.00,
            'legacy_score': 0.05,
            'consumption_ratio_score': 0.00,
            'coast_fire_score': 0.00,
            'accumulation_velocity_score': 0.00,
            'contribution_efficiency_score': 0.00,
        }
    },
    
    'die_with_zero': {
        'name': 'Die with Zero',
        'description': 'Maximize consumption, no legacy (inspired by Bill Perkins)',
        'detailed_description': """
**Who it's for:** Retirees who embrace Bill Perkins' "Die with Zero" philosophy—spend it all before you go.

**Philosophy:** You can't take it with you. This profile uniquely weights "Consumption Ratio" (30%), rewarding strategies that spend 
down capital aggressively while still ensuring income adequacy. Legacy is deliberately zeroed out—leaving money on the table is failure.

**Best for:** Childless retirees, those with charitable bequests already funded, or anyone prioritizing life experiences over inheritance.
        """,
        'emoji': '🎯',
        'applicable_categories': ['WITHDRAWAL_ONLY'],
        'category_label': 'withdrawal',
        'weights': {
            'pv_score': 0.25,
            'purchasing_power_score': 0.20,
            'stability_score': 0.10,
            'risk_score': 0.15,
            'robustness_score': 0.00,
            'capital_efficiency_score': 0.00,
            'legacy_score': 0.00,  # ZERO - defining trait
            'consumption_ratio_score': 0.30,  # DOMINANT
            'coast_fire_score': 0.00,
            'accumulation_velocity_score': 0.00,
            'contribution_efficiency_score': 0.00,
        }
    },
    
    'legacy_builder': {
        'name': 'Legacy Builder',
        'description': 'Maximize inheritance, minimize consumption',
        'detailed_description': """
**Who it's for:** Retirees who prioritize leaving wealth for heirs or charitable causes.

**Philosophy:** The goal is to pass on as much capital as possible while still living comfortably. 
This profile heavily weights legacy score (35%) while ensuring adequate income and risk management.

**Best for:** Those with adult children, philanthropists, or anyone valuing intergenerational wealth transfer.

**Key Metrics:**
- 35% Legacy Score (preserve and grow capital)
- 20% Risk Score (protect the inheritance)
- 15% Purchasing Power (maintain lifestyle)
- 10% Capital Efficiency (grow the legacy)
        """,
        'emoji': '👨‍👩‍👧‍👦',
        'applicable_categories': ['WITHDRAWAL_ONLY'],
        'category_label': 'withdrawal',
        'weights': {
            'pv_score': 0.10,
            'purchasing_power_score': 0.15,
            'stability_score': 0.10,
            'risk_score': 0.20,
            'robustness_score': 0.00,
            'capital_efficiency_score': 0.10,
            'legacy_score': 0.35,  # DOMINANT - leave money for heirs
            'consumption_ratio_score': 0.00,
            'coast_fire_score': 0.00,
            'accumulation_velocity_score': 0.00,
            'contribution_efficiency_score': 0.00,
        }
    },
    
    # ========================================
    # LIFECYCLE STRATEGIES (HYBRID)
    # ========================================
    'balanced_hybrid': {
        'name': 'Balanced Lifecycle',
        'description': 'Balanced performance across entire lifetime',
        'detailed_description': """
**Who it's for:** Users looking for a "set it and forget it" lifetime strategy.

**Philosophy:** Averages the priorities of accumulation and withdrawal. It ensures you grow wealth efficiently (Capital Efficiency) 
and then withdraw it safely (Risk/PV), without over-optimizing for either phase at the expense of the other.

**Key Metrics:**
- 20% Risk Score (Lifetime safety)
- 20% Capital Efficiency (Lifetime growth ROI)
- 20% Present Value (Lifetime spending)
- 15% Legacy Score (Terminal wealth)
- 15% Robustness (Works in all conditions)
- 10% Stability (Smooth income)
        """,
        'emoji': '⚖️',
        'applicable_categories': ['HYBRID'],
        'category_label': 'lifecycle',
        'weights': {
            'pv_score': 0.20,
            'purchasing_power_score': 0.00,
            'stability_score': 0.10,
            'risk_score': 0.20,
            'robustness_score': 0.15,
            'capital_efficiency_score': 0.20,
            'legacy_score': 0.15,
            'consumption_ratio_score': 0.00,
            'coast_fire_score': 0.00,
            'accumulation_velocity_score': 0.00,
            'contribution_efficiency_score': 0.00,
        }
    },
    'lifecycle_optimizer': {
        'name': 'Lifecycle Optimizer',
        'description': 'Balance accumulation and withdrawal phases',
        'detailed_description': """
**Who it's for:** Those using strategies that transition from saving to spending (e.g., target-date approaches).

**Philosophy:** Optimize across both accumulation and decumulation phases. This profile balances metrics 
that matter for wealth building (capital efficiency, Coast FIRE) with those critical for retirement (PV, stability, risk).

**Best for:** Target-date strategy users, glide-path strategists, or anyone with dynamic multi-phase approaches.

**Key Metrics:**
- 20% Present Value (total value across both phases)
- 20% Risk Score (protect in both phases)
- 15% Capital Efficiency (maximize growth when accumulating)
- 10% Stability (ensure smooth income when withdrawing)
        """,
        'emoji': '🔄',
        'applicable_categories': ['HYBRID'],
        'category_label': 'lifecycle',
        'weights': {
            'pv_score': 0.20,
            'purchasing_power_score': 0.10,
            'stability_score': 0.10,
            'risk_score': 0.20,
            'robustness_score': 0.05,
            'capital_efficiency_score': 0.15,
            'legacy_score': 0.10,
            'consumption_ratio_score': 0.00,
            'coast_fire_score': 0.05,
            'accumulation_velocity_score': 0.00,
            'contribution_efficiency_score': 0.05,
        }
    },
    
    'target_date_balanced': {
        'name': 'Target Date Balanced',
        'description': 'Optimize transition from growth to income',
        'detailed_description': """
**Who it's for:** Users with strategies that transition smoothly from accumulation to withdrawal (like target-date funds).

**Philosophy:** Ensure a balanced transition. Early years prioritize growth and efficiency, later years prioritize 
income stability and purchasing power. This profile weights metrics that matter for smooth phase transitions.

**Best for:** Those using glide-path strategies, age-based allocation adjusters, or dynamic rebalancers.

**Key Metrics:**
- 20% Risk Score (protect across the lifecycle)
- 15% each: Present Value, Purchasing Power, Stability (balanced priorities)
- 10% Robustness (works in all scenarios)
        """,
        'emoji': '🎯',
        'applicable_categories': ['HYBRID'],
        'category_label': 'lifecycle',
        'weights': {
            'pv_score': 0.15,
            'purchasing_power_score': 0.15,
            'stability_score': 0.15,
            'risk_score': 0.20,
            'robustness_score': 0.10,
            'capital_efficiency_score': 0.10,
            'legacy_score': 0.10,
            'consumption_ratio_score': 0.00,
            'coast_fire_score': 0.00,
            'accumulation_velocity_score': 0.00,
            'contribution_efficiency_score': 0.05,
        }
    },
    
    'adaptive_strategy': {
        'name': 'Adaptive Strategy',
        'description': 'Maximize flexibility across both phases',
        'detailed_description': """
**Who it's for:** Users with highly dynamic strategies that adapt based on market conditions, net worth thresholds, or other triggers.

**Philosophy:** Flexibility is key. This profile heavily weights robustness (15%) to ensure the strategy works 
in all market scenarios, while balancing growth potential and income adequacy.

**Best for:** Those using threshold-based strategies, market-adaptive approaches, or complex multi-phase logic.

**Key Metrics:**
- 20% Present Value (total value delivered)
- 15% each: Risk Score, Robustness, Capital Efficiency
- 10% Purchasing Power (maintain lifestyle)
        """,
        'emoji': '🧭',
        'applicable_categories': ['HYBRID'],
        'category_label': 'lifecycle',
        'weights': {
            'pv_score': 0.20,
            'purchasing_power_score': 0.10,
            'stability_score': 0.05,
            'risk_score': 0.15,
            'robustness_score': 0.15,  # High - must work in all scenarios
            'capital_efficiency_score': 0.15,
            'legacy_score': 0.10,
            'consumption_ratio_score': 0.00,
            'coast_fire_score': 0.05,
            'accumulation_velocity_score': 0.00,
            'contribution_efficiency_score': 0.05,
        }
    },
}


def recalculate_excellence_score(strategy_entry: Dict, profile_key: str = 'balanced') -> float:
    """
    Recalculate excellence score using a different weighting profile.
    Handles category-aware metrics that may be None for non-applicable strategies.
    
    Args:
        strategy_entry: Dict containing metric scores
        profile_key: Key for the weighting profile to use
    
    Returns:
        Recalculated excellence score (0-100)
    """
    if profile_key not in WEIGHTING_PROFILES:
        profile_key = 'balanced'
    
    weights = WEIGHTING_PROFILES[profile_key]['weights']
    
    # Filter out metrics where the score is None (not applicable)
    # and normalize the remaining weights to sum to 1.0
    applicable_scores = {}
    total_applicable_weight = 0.0
    
    for metric, weight in weights.items():
        score = strategy_entry.get(metric)
        if score is not None:  # Only include applicable metrics
            applicable_scores[metric] = score
            total_applicable_weight += weight
    
    # If no applicable metrics (edge case), return 0
    if total_applicable_weight == 0:
        return 0.0
    
    # Normalize weights and calculate score
    normalized_score = sum(
        applicable_scores[metric] * (weight / total_applicable_weight)
        for metric, weight in weights.items()
        if metric in applicable_scores
    )
    
    return round(normalized_score, 2)


def get_profile_options():
    """Returns list of profile display names for UI dropdown."""
    return [profile['name'] for profile in WEIGHTING_PROFILES.values()]


def get_profile_key_from_name(profile_name: str) -> str:
    """Convert display name to profile key."""
    for key, profile in WEIGHTING_PROFILES.items():
        if profile['name'] == profile_name:
            return key
    return 'balanced_accumulation'  # Default fallback


def get_profiles_for_category(category: str) -> List[str]:
    """
    Returns list of profile keys applicable to the given strategy category.
    
    Args:
        category: 'WITHDRAWAL_ONLY', 'CONTRIBUTION_ONLY', 'HYBRID', or None (all)
        
    Returns:
        List of profile keys that should be shown for this category
    """
    if category is None:
        # "All" category - return all profiles
        return list(WEIGHTING_PROFILES.keys())
    
    return [
        key for key, profile in WEIGHTING_PROFILES.items()
        if category in profile.get('applicable_categories', [])
    ]


def get_profiles_for_category_label(category_label: str) -> List[str]:
    """
    Returns profile keys for a specific category label (accumulation/withdrawal/lifecycle).
    
    Args:
        category_label: 'accumulation', 'withdrawal', 'lifecycle', or None (all)
        
    Returns:
        List of profile keys
    """
    if category_label is None:
        # All categories
        return list(WEIGHTING_PROFILES.keys())
    
    return [
        key for key, profile in WEIGHTING_PROFILES.items()
        if profile.get('category_label') == category_label or profile.get('category_label') is None
    ]


def get_profile_display_info(profile_key: str) -> Dict:
    """
    Get display information for a profile.
    
    Returns:
        Dict with 'name', 'emoji', 'description', 'category_label', 'applicable_categories'
    """
    profile = WEIGHTING_PROFILES.get(profile_key, WEIGHTING_PROFILES['balanced_accumulation'])
    return {
        'name': profile['name'],
        'emoji': profile.get('emoji', ''),
        'description': profile.get('description', ''),
        'category_label': profile.get('category_label'),
        'applicable_categories': profile.get('applicable_categories', []),
    }
